#cloud-config
hostname: ${hostname}
fqdn: ${fqdn}
prefer_fqdn_over_hostname: false
byobu_by_default: enable-system
packages:
  - openssh-server
  - snapd
  - jq
locale: C.UTF-8
users:
  - name: ubuntu
    lock_passwd: true
    shell: /bin/bash
    groups: [sudo]
    sudo: ALL=(ALL) NOPASSWD:ALL
  %{ if length(ssh_import_id) > 0 }
    ssh_import_id:
  %{ for id in ssh_import_id ~}
      - ${id}
  %{ endfor ~}
  %{ endif }